apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dmi-labeler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dmi-labeler
subjects:
  - kind: ServiceAccount
    name: dmi-labeler
    namespace: openshift-nodes
