apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dmi-labeler
  namespace: openshift-nodes
spec:
  template:
    spec:
      serviceAccountName: dmi-labeler
      containers:
        - name: labeler
          image: registry.access.redhat.com/ubi9/ubi-minimal
          command: ["/bin/bash", "-c"]
          args:
            - |
              while true; do
                PRODUCT_NAME=$(cat /sys/devices/virtual/dmi/id/product_name | tr ' ' '_')
                oc label node "$NODE_NAME" "feature.node.kubernetes.io/custom.dmi_product_name=$PRODUCT_NAME" --overwrite
                sleep 3600
              done
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: true
      volumes:
        - name: sys
          hostPath:
            path: /sys
            type: Directory
      restartPolicy: Always
