apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dmi-labeler
  namespace: openshift-nodes
spec:
  template:
    spec:
      serviceAccountName: dmi-labeler
      containers:
        - name: labeler
          image: registry.access.redhat.com/ubi9/ubi-minimal
          command: ["/bin/bash", "-c"]
          args:
            - |
              while true; do
                cd /sys/devices/virtual/dmi/id || exit 1
                for file in $(grep -l . * 2>/dev/null); do
                value=$(<"$file" tr -c 'a-zA-Z0-9' '_' | sed 's/_*$//')
                varname="${file//[^a-zA-Z0-9_]/_}"
                declare "$varname=$value"
                oc label node "$NODE_NAME" "feature.node.kubernetes.io/custom.dmi_$varname=$value" --overwrite
                sleep 86400
              done
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: true
      volumes:
        - name: sys
          hostPath:
            path: /sys
            type: Directory
      restartPolicy: Always
